// Generated by CoffeeScript 1.7.1
(function() {
  var addButtons, bisect, cell_padding, cell_size, cell_spacing, color, columns_container, container, doSearch, existing_oboe, font_size, fries, getOne, height, i, keep_fries_keys, keep_match_keys, links, margin, matrix_container, matrix_panel, mouseout, mouseover, n, panels, pc, rows_container, score_scale, svg, translate, updateAll, updateColumns, updateRows, vis_row, width, x, y;

  margin = {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0
  };

  cell_size = 10;

  n = 1e3;

  width = height = cell_size * n;

  addButtons = function(container) {
    var base_url, button_data;
    base_url = "//bostock.evl.uic.edu:8080/matches/score-above-zero/participant-b/";
    button_data = ["Uniprot:P27361", "Uniprot:P05412", "Uniprot:Q05397"];
    return container.append("div").classed("row", true).append("div").classed("col-xs-12", true).append("div").classed("panel panel-default", true).append("div").classed("panel-body", true).append("div").classed("btn-group", true).attr({
      "data-toggle": "buttons"
    }).call(function(div) {
      var label;
      label = div.selectAll("label").data(button_data);
      label.enter().append("label").classed("btn btn-primary", true).text(function(d) {
        return "Participant B: " + d;
      }).on("click", function(d) {
        return doSearch("" + base_url + d);
      });
      return label.append("input").attr({
        type: "radio",
        name: "data"
      });
    });
  };

  translate = function(x, y) {
    return "translate (" + x + "," + y + ")";
  };

  fries = [];

  pc = [];

  links = [];

  doSearch = function(url) {
    var existing_oboe;
    fries = [];
    pc = [];
    links = [];
    matrix_container.selectAll(".row").remove();
    if (typeof existing_oboe !== "undefined" && existing_oboe !== null) {
      existing_oboe.abort();
    }
    return existing_oboe = oboe(url).node("!.*", function(card) {
      var new_card, source_fries, source_index;
      source_fries = new_card = {};
      keep_fries_keys.forEach(function(key) {
        return new_card[key] = card[key];
      });
      source_index = bisect(fries, new_card);
      fries.splice(source_index, 0, new_card);
      card.match.forEach(function(match) {
        var match_data, target_index, target_pc;
        if (match.score === 0) {
          return;
        }
        target_index = _.findIndex(pc, function(d) {
          return d._id === match._id;
        });
        if (target_index === -1) {
          target_pc = new_card = {
            _id: match._id
          };
          target_index = bisect(pc, new_card);
          pc.splice(target_index, 0, new_card);
        } else {
          target_pc = pc[target_index];
        }
        match_data = {};
        keep_match_keys.forEach(function(key) {
          return match_data[key] = match[key];
        });
        return links.push({
          source: source_fries,
          target: target_pc,
          match_data: match_data
        });
      });
      return updateAll();
    });
  };

  x = d3.scale.ordinal();

  y = d3.scale.ordinal();

  cell_spacing = 0;

  cell_padding = 0;

  updateAll = function() {
    cell_size = parseInt(svg.style("width")) / pc.length;
    cell_padding = cell_size > 3 ? 2 : 0;
    y.domain(d3.range(fries.length)).rangeBands([0, cell_size * fries.length], cell_spacing);
    x.domain(d3.range(pc.length)).rangeBands([0, cell_size * pc.length], cell_spacing);
    svg.style({
      height: cell_size * fries.length
    });
    updateRows(fries);
    return updateColumns(pc);
  };

  updateAll = _.throttle(updateAll, 100);

  font_size = "9px";

  color = d3.scale.category10();

  score_scale = d3.scale.linear().domain([0, 10]).range([0, 0.6]);

  getOne = function(json) {
    return new Promise(function(resolve) {
      return d3.xhr("//bostock.evl.uic.edu:8080/get-one", "application/json").header("Content-Type", "application/json").on("load", resolve).post(JSON.stringify(json));
    });
  };

  mouseover = function(d) {
    var text;
    d3.select(this).classed("highlight", true);
    getOne({
      _id: d.source._id,
      collection: "fries_cards"
    }).then(function(d) {
      var json, text;
      json = JSON.parse(d.response);
      text = JSON.stringify(json, null, 2);
      return d3.select(".fries-data .text").text(text);
    });
    getOne({
      _id: d.target._id,
      collection: "pc_cards"
    }).then(function(d) {
      var text;
      text = JSON.stringify(JSON.parse(d.response), null, 2);
      return d3.select(".pc-data .text").text(text);
    });
    text = JSON.stringify(d.match_data, null, 2);
    return d3.select(".match-data").selectAll("tr").each(function(row) {
      var string, td;
      string = d.match_data[row.key];
      td = d3.select(this).selectAll(".hover-data").data([string]);
      td.enter().append("td").classed("hover-data", true);
      td.text(string);
      if (row.key === "deltaFeature") {
        td.style({
          color: function(d) {
            return color(string);
          }
        });
      }
      if (row.key === "potentialConflict") {
        return td.style({
          color: function(d) {
            if (string === true) {
              return "red";
            } else {
              return "black";
            }
          }
        });
      }
    });
  };

  mouseout = function(d) {
    d3.select(this).classed("highlight", false);
    d3.select(".fries-data .text").text("");
    d3.select(".pc-data .text").text("");
    return d3.select(".match-data").selectAll(".hover-data").text("");
  };

  updateRows = function(fries) {
    var cells, rows;
    rows = rows_container.selectAll(".row").data(fries);
    rows.enter().append("g").classed("row", true).append("text").text(function(d) {
      return d._filename;
    }).attr({
      dy: font_size
    }).style({
      "font-size": font_size,
      "text-anchor": "end"
    });
    rows.attr({
      transform: function(d, i) {
        return translate(0, y(i));
      }
    });
    rows.exit().remove();
    cells = rows.selectAll(".cell").data(function(card) {
      return links.filter(function(link) {
        return link.source === card;
      });
    });
    cells.enter().append("g").classed("cell", true).on("mouseover", mouseover).on("mouseout", mouseout).append("rect");
    return cells.attr({
      transform: function(link) {
        var index;
        index = pc.indexOf(link.target);
        if (index === -1) {
          throw new Error("Can't find link target.");
        }
        return translate(x(index), 0);
      }
    }).select("rect").attr({
      width: x.rangeBand() - cell_padding,
      height: y.rangeBand() - cell_padding,
      x: cell_padding / 2,
      y: cell_padding / 2
    }).style({
      opacity: function(d) {
        return score_scale(d.match_data.score);
      }
    }).style({
      fill: function(d) {
        if (d.match_data.potentialConflict) {
          return "red";
        } else {
          return color(d.match_data.deltaFeature);
        }
      }
    });
  };

  updateColumns = function(pc) {
    var columns;
    columns = columns_container.selectAll(".column").data(pc);
    return columns.enter().append("g").classed("column", true).append("text").text(function(d) {
      return d._id;
    }).attr({
      dy: font_size
    }).style({
      "font-size": font_size
    }).attr({
      transform: function(d, i) {
        return translate(x(i), 0) + "rotate(-90)";
      }
    });
  };

  container = d3.select("body").append("main").append("div").classed("container", true).style({
    "padding-top": "10px"
  }).call(addButtons);

  vis_row = container.append("div").classed("row", true);

  matrix_panel = vis_row.append("div").classed("col-xs-6", true).append("div").classed("panel panel-default", true).append("div").classed("panel-body", true);

  panels = [
    {
      label: "Match Data",
      klass: "match-data",
      keys: [
        {
          key: "deltaFeature",
          label: "Delta Feature"
        }, {
          key: "potentialConflict",
          label: "Potential Conflict?"
        }, {
          key: "participantA",
          label: "Participant A"
        }, {
          key: "score",
          label: "Score"
        }
      ]
    }, {
      label: "FRIES Data",
      klass: "fries-data",
      keys: [
        {
          key: "_participant_a_ids",
          label: "Participant A"
        }, {
          key: "_participant_b_ids",
          label: "Participant B"
        }
      ]
    }, {
      label: "PC Data",
      klass: "pc-data",
      keys: [
        {
          key: "_participant_a_ids",
          label: "Participant A"
        }, {
          key: "_participant_b_ids",
          label: "Participant B"
        }
      ]
    }
  ];

  vis_row.append("div").classed("col-xs-6", true).selectAll(".panel").data(panels).enter().append("div").attr("class", function(d) {
    return d.klass;
  }).classed("panel panel-default", true).call(function(div) {
    div.append("div").classed("panel-heading", true).text(function(d) {
      return d.label;
    });
    div.append("table").classed("table table-condensed", true).append("tbody").selectAll("tr").data(function(d) {
      return d.keys || [];
    }).enter().append("tr").append("td").text(function(d) {
      return d.label;
    });
    div.append("div").classed("panel-body", true);
    return div.append("pre").classed("text", true).style({
      height: "250px",
      overflow: "scroll"
    });
  }).each(function(d) {
    if (d.klass === "match-data") {
      d3.select(this).select("pre").remove();
      return d3.select(this).select(".panel-body").remove();
    }
  });

  svg = matrix_panel.append("svg").attr({
    width: "100%",
    height: "500px"
  });

  svg.append("rect").style({
    fill: "none",
    stroke: "black"
  }).attr({
    width: "100%",
    height: "100%"
  });

  matrix_container = svg.append("g").attr({
    "transform": translate(margin.left, margin.top)
  });

  matrix_container.append("rect").attr({
    width: "100%",
    height: "100%"
  }).style({
    fill: "#eee"
  });

  rows_container = matrix_container.append("g").classed("rows", true);

  columns_container = matrix_container.append("g").classed("columns", true);

  fries = [];

  pc = [];

  links = [];

  bisect = d3.bisector(function(d) {
    return d._id;
  }).left;

  keep_fries_keys = ["_id", "_filename", "_participant_a_ids", "_participant_b_ids"];

  keep_match_keys = ["deltaFeature", "potentialConflict", "participantA", "score"];

  i = 0;

  existing_oboe = null;

  container.selectAll("label").each(function(d, i) {
    if (i === 0) {
      d3.select(this).node().click();
    }
    if (d === "Uniprot:P27361") {
      d3.select(this).select("a").append("span").text(" (includes potentialConflict)");
    }
    if (d === "Uniprot:P00533") {
      return d3.select(this).select("a").append("span").text(" (demonstrates scaling issues)");
    }
  });

}).call(this);
