// Generated by CoffeeScript 1.10.0
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.use(express["static"](__dirname));

  app.listen(process.env.PORT, process.env.IP);

}).call(this);
