// Generated by CoffeeScript 1.9.3
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.use(express["static"](__dirname));

  // server = app.listen(process.env.PORT, function() {
  //     console.log(server.address().address, server.address().port);
  // });
  
  server = app.listen(8080, function() {
      console.log(server.address().address, server.address().port);
  });

}).call(this);
