// Generated by CoffeeScript 1.7.1
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.use(express["static"](__dirname));

  server = app.listen(process.env.PORT, function() {
      console.log(server.address().address, server.address().port);
  });

}).call(this);
